name: test

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: ${{ matrix.command }} nim${{ matrix.version }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.6.x
          - 2.2.x
        command:
          - nimble check
          - nimble format && git diff --exit-code
          - nimble lint
          - nimble test
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jiro4989/setup-nim-action@cb1fc1270b117457dd0d9f610ec981fad3369cec # v2.3.0
        with:
          nim-version: ${{ matrix.version }}
          nim-install-directory: nim
          parent-nim-install-directory: /opt
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install
      - run: ${{ matrix.command }}
